### ISSUE TITLE
SideWaffle throws FileNotFoundException

### ISSUE THREAD

**Issue by dreammaster38** [ligershark/sidewafflev2#41]
Hi,

I have installed Visual Studio 2017 V15.9.11 and Visual Studio 2019 V16.0 side by side.
After upgrading SideWaffle to V1.1 for both Versions of VS I get this exception in VS 2017:

CreateInstance failed for package [SideWaffleCreatorPackage]Source: 'mscorlib' Description: The file or assembly "Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or a dependency on it was not found. The system cannot find the specified file.
System.IO.FileNotFoundException: The file or assembly "Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or a dependency was not found. The system cannot find the specified file.
File name: 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)

**Comment by bsubasic** [comment]
+1

**Comment by sayedihashimi** [comment]
I have a new version at https://www.dropbox.com/s/ah9b7zusp5itr3a/SideWaffle.Creator.vsix?dl=0 can you try it out and let me know if it's working for you. If so I will publish it to the gallery.

**Comment by bsubasic** [comment]
It works, no error.

**Comment by sayedihashimi** [comment]
@bsubasic thanks, I have uploaded that version to the gallery. I'll go ahead and close this now but please reopen if there are further issues.
